apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-function-get-credential-data
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      credentials:
        - name: foo-creds
          secretRef:
            name: foo-creds
            namespace: default
          source: Secret
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: Context
            data:
              username: {{ ( getCredentialData . "foo-creds" ).username | toString }}
              password: {{ ( getCredentialData . "foo-creds" ).password | toString }}
