apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-read-file
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: FileSystem
        filesystem:
          dirPath: ./templates
