apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: useraccesskeys-go-templating
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: iam.aws.m.upbound.io/v1beta1
            kind: User
            metadata:
              annotations:
                {{ setResourceNameAnnotation "user" }}
            spec:
              forProvider: {}
            ---
            apiVersion: iam.aws.m.upbound.io/v1beta1
            kind: AccessKey
            metadata:
              annotations:
                {{ setResourceNameAnnotation "accesskey-0" }}
            spec:
              forProvider:
                userSelector:
                  matchControllerRef: true
              writeConnectionSecretToRef:
                name: {{ $.observed.composite.resource.metadata.name }}-accesskey-secret-0
            ---
            apiVersion: iam.aws.m.upbound.io/v1beta1
            kind: AccessKey
            metadata:
              annotations:
                {{ setResourceNameAnnotation "accesskey-1" }}
            spec:
              forProvider:
                userSelector:
                  matchControllerRef: true
              writeConnectionSecretToRef:
                name: {{ $.observed.composite.resource.metadata.name }}-accesskey-secret-1
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ dig "spec" "writeConnectionSecretToRef" "name" "" $.observed.composite.resource }}
              annotations:
                {{ setResourceNameAnnotation "connection-secret" }}
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            {{ $accesskey0 := getComposedConnectionDetails . "accesskey-0" }}
            {{ $accesskey1 := getComposedConnectionDetails . "accesskey-1" }}
            data:
              user-0: {{ index $accesskey0 "username" }}
              user-1: {{ index $accesskey1 "username" }}
              password-0: {{ index $accesskey0 "password" }}
              password-1: {{ index $accesskey1 "password" }}
            {{ end }}
