apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-function-tpl
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{$vals:= .observed.composite.resource.spec}}
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx-deployment
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: test1
              labels:
                {{- toYaml (tpl $vals.labels $vals) | nindent 4}}
            spec:
              replicas: 3
              selector:
                matchLabels:
                  {{- toYaml (tpl $vals.labels $vals) | nindent 6}}
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - name: nginx
                    image: nginx:1.14.2
                    ports:
                    - containerPort: 80
