apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-function-to-json
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: {{ .observed.composite.resource.kind }}
            status:
              # Marshall whole 'complexDictionary' as json string
              dummy: {{ .observed.composite.resource.spec.complexDictionary | toJson | quote }}
