apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
kind: FlexibleServer
metadata:
  annotations:
    crossplane.io/composition-resource-name: flexServer
  labels:
    crossplane.io/composite: example
spec:
  forProvider:
    storageMb: 32768
  providerConfigRef:
    name: my-provider-cfg
status:
  atProvider:
    id: abcdef
  conditions:
    - type: Ready
      status: "True"
      reason: "foo"
      lastTransitionTime: "2023-11-03T09:07:31Z"
